#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_APP_USER}'
  ) THEN
    CREATE ROLE ${POSTGRES_APP_USER} LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
  ELSE
    ALTER ROLE ${POSTGRES_APP_USER} WITH LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
  END IF;
END
\$\$;

DO
\$\$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '${GHOST_DB_USER}'
  ) THEN
    CREATE ROLE ${GHOST_DB_USER} LOGIN PASSWORD '${GHOST_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${GHOST_DB_USER} WITH LOGIN PASSWORD '${GHOST_DB_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${POSTGRES_APP_DB} OWNER ${POSTGRES_APP_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_APP_DB}')
\gexec

SELECT 'CREATE DATABASE ${GHOST_DB} OWNER ${GHOST_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${GHOST_DB}')
\gexec
EOSQL
